# Generated by Django 2.1.4 on 2019-01-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190107_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='', upload_to='../media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='filemeta',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filemeta',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='filemeta',
            name='image',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
    ]
