# Generated by Django 2.1.4 on 2019-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190108_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemeta',
            old_name='image',
            new_name='file',
        ),
    ]
