# Generated by Django 2.1.4 on 2019-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190108_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemeta',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
